package com.eventflow.backend.entity;

public enum NotiType {
    UPCOMING,
    OVERDUE,
    TASK_ASSIGNED,
    TASK_UPDATED,
    TASK_REVIEW_REQUESTED,
    TASK_REVIEWED,
    CALENDAR_INVITE,
    CALENDAR_UPDATED,
    CALENDAR_REMINDER_TOMORROW,
    CALENDAR_REMINDER_SOON
}
