package com.eventflow.backend.service;

import com.eventflow.backend.dto.CategoryMetricDTO;
import com.eventflow.backend.repository.DashboardRepository;
import com.eventflow.backend.repository.DepartmentRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.time.LocalDate;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

class DashboardServiceTest {

    private DashboardService dashboardService;
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:dashboard-service;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                "");
        jdbcTemplate = new JdbcTemplate(dataSource);
        dashboardService = new DashboardService(
                mock(DashboardRepository.class),
                mock(DepartmentRepository.class),
                jdbcTemplate);

        jdbcTemplate.execute("DROP TABLE IF EXISTS task_status_history");
        jdbcTemplate.execute("DROP TABLE IF EXISTS tasks");
        jdbcTemplate.execute("""
                CREATE TABLE tasks (
                    id BIGINT PRIMARY KEY,
                    event_id BIGINT NOT NULL,
                    department_id BIGINT,
                    parent_id BIGINT,
                    status VARCHAR(50) NOT NULL,
                    deadline TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE task_status_history (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    task_id BIGINT NOT NULL,
                    event_id BIGINT NOT NULL,
                    department_id BIGINT,
                    status VARCHAR(50) NOT NULL,
                    changed_at TIMESTAMP NOT NULL
                )
                """);
    }

    @Test
    void getEventTasksByStatusUsesStatusHistoryWhenDateRangeIsProvided() {
        jdbcTemplate.update("INSERT INTO tasks (id, event_id, status, deadline) VALUES (1, 2, 'DONE', '2026-08-01 09:00:00')");
        jdbcTemplate.update("INSERT INTO tasks (id, event_id, status, deadline) VALUES (2, 2, 'IN_PROGRESS', '2026-08-02 09:00:00')");
        jdbcTemplate.update("INSERT INTO task_status_history (task_id, event_id, status, changed_at) VALUES (1, 2, 'DONE', '2026-06-16 10:00:00')");
        jdbcTemplate.update("INSERT INTO task_status_history (task_id, event_id, status, changed_at) VALUES (2, 2, 'TODO', '2026-06-20 10:00:00')");
        jdbcTemplate.update("INSERT INTO task_status_history (task_id, event_id, status, changed_at) VALUES (2, 2, 'IN_PROGRESS', '2026-06-22 10:00:00')");

        List<CategoryMetricDTO> result = dashboardService.getEventTasksByStatus(
                2L,
                LocalDate.of(2026, 6, 15),
                LocalDate.of(2026, 6, 21));

        assertThat(result).extracting(CategoryMetricDTO::getLabel).containsExactly("TODO", "DONE");
        assertThat(result).extracting(CategoryMetricDTO::getTotalTasks).containsExactly(1L, 1L);
    }
}